# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

#ZSH_THEME=powerlevel10k/powerlevel10k

#source $ZSH/oh-my-zsh.sh

export PATH=$HOME/bin:/usr/local/bin:$PATH

# zplug configruation
if [[ ! -d "${ZPLUG_HOME}" ]]; then
  if [[ ! -d ~/.zplug ]]; then
    git clone https://github.com/zplug/zplug ~/.zplug
    # If we can't get zplug, it'll be a very sobering shell experience. To at
    # least complete the sourcing of this file, we'll define an always-false
    # returning zplug function.
    if [[ $? != 0 ]]; then
      function zplug() {
        return 1
      }
    fi
  fi
  export ZPLUG_HOME=~/.zplug
fi
if [[ -d "${ZPLUG_HOME}" ]]; then
  source "${ZPLUG_HOME}/init.zsh"
fi
zplug 'plugins/git', from:oh-my-zsh, if:'which git'
#zplug 'denisidoro/navi'
zplug 'supercrabtree/k'
#zplug 'romkatv/powerlevel10k', use:powerlevel10k.zsh-theme
zplug 'romkatv/powerlevel10k', as:theme, depth:1, use:powerlevel10k.zsh-theme
zplug "MichaelAquilina/zsh-you-should-use"
#zplug "changyuheng/zsh-interactive-cd"
#zplug "plugins/vi-mode", from:oh-my-zsh
zplug 'zsh-users/zsh-autosuggestions'
#zplug 'zsh-users/zsh-completions', defer:2
#zplug 'zsh-users/zsh-history-substring-search'
zplug 'zsh-users/zsh-syntax-highlighting', defer:2

if ! zplug check; then
  zplug install
fi

zplug load

setopt nonomatch
alias .='cd $HOME'
#alias g=k
alias l=k
alias ll='ls -laa'
alias pacman='sudo pacman'
alias zshconfig='nvim $HOME/.zshrc'
alias nvimconfig='nvim $HOME/.config/nvim/init.vim'
alias v2raya='sudo v2raya'

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
